apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: testcode-aws-secrets-manager         # 이름 주의 (external-secret.yaml 확인)
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
      auth:
        jwt:
          serviceAccountRef:
            name: secrets-sa                # IRSA가 적용된 서비스 계정
            namespace: testcode-namespace
