apiVersion: v1
kind: Service
metadata:
  name: testcode-svc
  namespace: testcode-namespace
spec:
  ports:
  - name: 8080-5000
    port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    app: testcode
  type: ClusterIP
